spring:
  datasource:    driver-class-name: org.h2.Driver
    username: sa
    password:
    url: jdbc:h2:tcp://localhost/~/test
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      use-new-id-generator-mappings: true
      ddl-auto: update
  h2:
    database-platform: H2    console:      enabled: true
server:  port: 9090
